FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04

LABEL maintainer "BMW Group"
# The commands below install Cuda and libcudnn in order for the code to run on the GPU
ENV CUDNN_VERSION 7.4.2.24
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"
ARG DEBIAN_FRONTEND=noninteractive


# Fix Nvidia/Cuda repository key rotation
RUN sed -i '/developer\.download\.nvidia\.com\/compute\/cuda\/repos/d' /etc/apt/sources.list.d/*
RUN sed -i '/developer\.download\.nvidia\.com\/compute\/machine-learning\/repos/d' /etc/apt/sources.list.d/*  
RUN apt-key del 7fa2af80 &&\
    apt-get update && \
    apt-get  install -y wget && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb
    





RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        git \
        wget \
	    cuda-command-line-tools-10-0 \
        cuda-cublas-10-0 \
        cuda-cufft-10-0 \
        cuda-curand-10-0 \
        cuda-cusolver-10-0 \
        cuda-cusparse-10-0 \
        locales \
        python3 \
        python3-pip \
        wget \
        pkg-config\
        curl\
        docker.io \
        python3-dev

RUN pip3 install -U pip

RUN pip3 install setuptools
RUN pip3 install  docker GPUtil fastapi[all]



# Set the locale (required for uvicorn)
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
  dpkg-reconfigure --frontend=noninteractive locales && \
  update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8 

COPY ./api /api

WORKDIR /api

CMD uvicorn main:app --host 0.0.0.0  --port 2223
