version: '2.3'

services:

  docker_sdk:
    image: classification_docker_sdk
    network_mode: "host"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker_sdk_api/api:/api
      - ./data:/datasets
      - ./servable:/servable
      - ./checkpoints:/checkpoints
      - ./models:/models


  user_interface:
    image: classification_gui
    ports:
      - "4200:80"
  
  inference_api:
    image: classification_inference_api
    volumes:
      - ./models:/models
      - ./inference_api/src/main:/main
    ports:
      - "4343:4343"